### ISSUE TITLE
Use custom renderInput

### ISSUE THREAD

**Issue by PantherX99** [Mihaiii/semantic-autocomplete#1]
The component does not use the provided renderInput component and overwrites it with its own renderLoadingInput function. This causes layout shifts, if the mui Autocomplete size is set to small but the CircularProgress uses its default size.

```
renderInput={(params) => (
    <TextField
        {...params}
        InputProps={{
            ...params.InputProps,
            endAdornment: (
                <Fragment>
                    {loading ? <CircularProgress color="inherit" size={20} /> : null}
                    {params.InputProps.endAdornment}
                </Fragment>
            ),
        }}
    />
)}
size='small'
```

Is the built in renderLoadingInput function even necessary?

**Comment by Mihaiii** [comment]
> if the mui Autocomplete size is set to small but the CircularProgress uses its default size.

Indeed, thanks. I'll make a change adjusting the size of the CircularProgress element.

> Is the built in renderLoadingInput function even necessary?

The whole idea here is to provide a visual hint while the model is loaded and embeddings are computed. Let me know if you have a better idea.
